# Generated by Django 4.1.6 on 2023-12-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radiologist',
            fields=[
                ('radiologist_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Radiologist ID')),
                ('radiologist_username', models.CharField(max_length=100, verbose_name='Username')),
                ('radiologist_firstname', models.CharField(max_length=100, verbose_name='First Name')),
                ('radiologist_lastname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('radiologist_password', models.CharField(max_length=100, verbose_name='Password')),
                ('radiologist_email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='RawXray',
            fields=[
                ('raw_cxray_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Raw CXray Image ID')),
                ('raw_cxray_filename', models.CharField(max_length=100, verbose_name='Raw CXRay File Name')),
                ('raw_cxray', models.FileField(upload_to='', verbose_name='Raw CXray Image')),
            ],
        ),
    ]
