# Generated by Django 4.1.6 on 2023-09-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radiologist',
            fields=[
                ('radiologist_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Radiologist ID')),
                ('radiologist_name', models.CharField(max_length=100, verbose_name='Name')),
                ('radiologist_email', models.CharField(max_length=100, verbose_name='Email')),
                ('radiologist_username', models.CharField(max_length=100, verbose_name='Username')),
                ('radiologist_password', models.CharField(max_length=100, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='RawXray',
            fields=[
                ('raw_cxray_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Raw CXray Image ID')),
                ('raw_cxray_name', models.CharField(max_length=100, verbose_name='Raw CXRay Name')),
                ('raw_cxray', models.FileField(upload_to='media/', verbose_name='Raw CXray Image')),
            ],
        ),
    ]
