# Generated by Django 4.1.6 on 2023-11-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CXRaide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawxray',
            name='raw_cxray',
            field=models.FileField(upload_to='', verbose_name='Raw CXray Image'),
        ),
        migrations.AlterField(
            model_name='rawxray',
            name='raw_cxray_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Raw CXRay Name'),
        ),
    ]
